---
namespace: "tehtbl"
name: "provisioning"
version: "0.0.1"
readme: "README.md"

authors:
  - "@tehtbl <3999809+tehtbl@users.noreply.github.com>"

description: An Ansible collection to provision a host and prepare it for their later use.

# Either a single license or a list of licenses for content inside of a collection. Ansible Galaxy currently only
# accepts L(SPDX,https://spdx.org/licenses/) licenses. This key is mutually exclusive with 'license_file'
# license:
# - GPL-2.0-or-later

# The path to the license file for the collection. This path is relative to the root of the collection. This key is
# mutually exclusive with 'license'
license_file: LICENSE.md

# A list of tags you want to associate with the collection for indexing/searching. A tag name has the same character
# requirements as 'namespace' and 'name'
tags:
  - system
  - provisioning
  - bootstrap
  - server

dependencies:
  ansible.posix: "1.4.0"
  community.general: "5.0.0"
  geerlingguy.docker: "4.2.4"

repository: https://github.com/tehtbl/ansible-collection-tehtbl-provisioning.git
documentation: https://github.com/tehtbl/ansible-collection-tehtbl-provisioning
homepage: https://github.com/tehtbl/ansible-collection-tehtbl-provisioning
issues: https://github.com/tehtbl/ansible-collection-tehtbl-provisioning/issues

build_ignore: []
